// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: submodule-for-timecapsule/timeline_service/custom_event.proto

package timeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomEvent represents a user-defined event for the timeline.
type CustomEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Date        string `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Category    string `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt   string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *CustomEvent) Reset() {
	*x = CustomEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEvent) ProtoMessage() {}

func (x *CustomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEvent.ProtoReflect.Descriptor instead.
func (*CustomEvent) Descriptor() ([]byte, []int) {
	return file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescGZIP(), []int{0}
}

func (x *CustomEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CustomEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CustomEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomEvent) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CustomEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CustomEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CustomEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// GetCustomEventByIdRequest represents a request to retrieve a custom event by its ID.
type GetCustomEventByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCustomEventByIdRequest) Reset() {
	*x = GetCustomEventByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCustomEventByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomEventByIdRequest) ProtoMessage() {}

func (x *GetCustomEventByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomEventByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCustomEventByIdRequest) Descriptor() ([]byte, []int) {
	return file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomEventByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteCustomEventRequest represents a request to delete a custom event by its ID.
type DeleteCustomEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCustomEventRequest) Reset() {
	*x = DeleteCustomEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCustomEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomEventRequest) ProtoMessage() {}

func (x *DeleteCustomEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomEventRequest) Descriptor() ([]byte, []int) {
	return file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCustomEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteCustomEventResponse represents a response to a custom event deletion request.
type DeleteCustomEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteCustomEventResponse) Reset() {
	*x = DeleteCustomEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCustomEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomEventResponse) ProtoMessage() {}

func (x *DeleteCustomEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteCustomEventResponse) Descriptor() ([]byte, []int) {
	return file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCustomEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetAllCustomEventsRequest represents a request to retrieve all custom events.
type GetAllCustomEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page        int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit       int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	UserId      string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // Filter by user ID
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                          // Filter by title
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`              // Filter by description
	Category    string `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`                    // Filter by category
	StartDate   string `protobuf:"bytes,7,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Filter by start date (inclusive)
	EndDate     string `protobuf:"bytes,8,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // Filter by end date (inclusive)
}

func (x *GetAllCustomEventsRequest) Reset() {
	*x = GetAllCustomEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCustomEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCustomEventsRequest) ProtoMessage() {}

func (x *GetAllCustomEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCustomEventsRequest.ProtoReflect.Descriptor instead.
func (*GetAllCustomEventsRequest) Descriptor() ([]byte, []int) {
	return file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllCustomEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllCustomEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllCustomEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllCustomEventsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAllCustomEventsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetAllCustomEventsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetAllCustomEventsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetAllCustomEventsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// GetAllCustomEventsResponse represents a response containing a list of custom events.
type GetAllCustomEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomEvents []*CustomEvent `protobuf:"bytes,1,rep,name=custom_events,json=customEvents,proto3" json:"custom_events,omitempty"`
	Count        int32          `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllCustomEventsResponse) Reset() {
	*x = GetAllCustomEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCustomEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCustomEventsResponse) ProtoMessage() {}

func (x *GetAllCustomEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCustomEventsResponse.ProtoReflect.Descriptor instead.
func (*GetAllCustomEventsResponse) Descriptor() ([]byte, []int) {
	return file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllCustomEventsResponse) GetCustomEvents() []*CustomEvent {
	if x != nil {
		return x.CustomEvents
	}
	return nil
}

func (x *GetAllCustomEventsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_submodule_for_timecapsule_timeline_service_custom_event_proto protoreflect.FileDescriptor

var file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x66, 0x6f, 0x72, 0x2d,
	0x74, 0x69, 0x6d, 0x65, 0x63, 0x61, 0x70, 0x73, 0x75, 0x6c, 0x65, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0xdc, 0x01, 0x0a, 0x0b, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x35, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xec, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x6e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa5, 0x02, 0x0a, 0x12, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x5c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x13, 0x5a, 0x11, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescOnce sync.Once
	file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescData = file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDesc
)

func file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescGZIP() []byte {
	file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescOnce.Do(func() {
		file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescData)
	})
	return file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDescData
}

var file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_submodule_for_timecapsule_timeline_service_custom_event_proto_goTypes = []any{
	(*CustomEvent)(nil),                // 0: timeline.CustomEvent
	(*GetCustomEventByIdRequest)(nil),  // 1: timeline.GetCustomEventByIdRequest
	(*DeleteCustomEventRequest)(nil),   // 2: timeline.DeleteCustomEventRequest
	(*DeleteCustomEventResponse)(nil),  // 3: timeline.DeleteCustomEventResponse
	(*GetAllCustomEventsRequest)(nil),  // 4: timeline.GetAllCustomEventsRequest
	(*GetAllCustomEventsResponse)(nil), // 5: timeline.GetAllCustomEventsResponse
}
var file_submodule_for_timecapsule_timeline_service_custom_event_proto_depIdxs = []int32{
	0, // 0: timeline.GetAllCustomEventsResponse.custom_events:type_name -> timeline.CustomEvent
	1, // 1: timeline.CustomEventService.GetCustomEventById:input_type -> timeline.GetCustomEventByIdRequest
	2, // 2: timeline.CustomEventService.DeleteCustomEvent:input_type -> timeline.DeleteCustomEventRequest
	4, // 3: timeline.CustomEventService.GetAllCustomEvents:input_type -> timeline.GetAllCustomEventsRequest
	0, // 4: timeline.CustomEventService.GetCustomEventById:output_type -> timeline.CustomEvent
	3, // 5: timeline.CustomEventService.DeleteCustomEvent:output_type -> timeline.DeleteCustomEventResponse
	5, // 6: timeline.CustomEventService.GetAllCustomEvents:output_type -> timeline.GetAllCustomEventsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_submodule_for_timecapsule_timeline_service_custom_event_proto_init() }
func file_submodule_for_timecapsule_timeline_service_custom_event_proto_init() {
	if File_submodule_for_timecapsule_timeline_service_custom_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CustomEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetCustomEventByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteCustomEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteCustomEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllCustomEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllCustomEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submodule_for_timecapsule_timeline_service_custom_event_proto_goTypes,
		DependencyIndexes: file_submodule_for_timecapsule_timeline_service_custom_event_proto_depIdxs,
		MessageInfos:      file_submodule_for_timecapsule_timeline_service_custom_event_proto_msgTypes,
	}.Build()
	File_submodule_for_timecapsule_timeline_service_custom_event_proto = out.File
	file_submodule_for_timecapsule_timeline_service_custom_event_proto_rawDesc = nil
	file_submodule_for_timecapsule_timeline_service_custom_event_proto_goTypes = nil
	file_submodule_for_timecapsule_timeline_service_custom_event_proto_depIdxs = nil
}
